- name: Install Jenkins on Rocky Linux with Java 17
  hosts: all
  become: yes
  vars:
    jenkins_repo_url: http://pkg.jenkins.io/redhat-stable/jenkins.repo
    jenkins_repo_key_url: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

  tasks:
    - name: Ensure the system is updated
      yum:
        name: "*"
        state: latest

    - name: Install Java 17 (required by Jenkins)
      yum:
        name: java-17-openjdk
        state: present

    - name: Add Jenkins repository
      get_url:
        url: "{{ jenkins_repo_url }}"
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins repository key
      rpm_key:
        state: present
        key: "{{ jenkins_repo_key_url }}"

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Open firewall for Jenkins (port 8080)
      firewalld:
        permanent: yes
        immediate: yes
        state: enabled
        port: 8080/tcp

    - name: Reload firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded

    - name: Get Jenkins initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_initial_password

    - name: Display Jenkins initial admin password
      debug:
        msg: "Jenkins initial admin password is: {{ jenkins_initial_password.stdout }}"
